mdx-editor/editor

src/plugins/table/TableNode.tsx
#53 : Fixed application error when deleting the final row of a table directly
=> #53: Update TableNode.tsx to delete the last row properly

src/MDXEditor.tsx
Lets user specify where to trigger focus
=> feat: let user choose where to manually focus

src/index.ts
=> chore: export the Code Mirror editor

src/styles/lexical-theme.module.css
We need to add style for nestedListItem otherwise the nest check list won't be shown correctly.
=> Add style for nestedListItem

docs/getting-started.md
Fixed broken link to the CRA example repo.
Added example for CRA
=> Fix broken CRA example link

src/plugins/image/index.ts
I prepared a PR similar to link-dialog
=> Add custom image dialog

package.json
When I compiled locally, I found that a dependency was missing.
=> Add a dependency

package-lock.json, src/MDXEditor.tsx
=> Trimming classNames before split

locales/zh-cn/translation.json
Added translation resource file for locale "Chinese (Simplified)"
=> feat: add Chinese(Simplified) language translation

src/plugins/core/index.ts
Contains the fix for [503](https://github.com/mdx-editor/editor/issues/503)
=> Export importVisitors$, usedLexicalNodes$, usedLexicalNodes$ cells

locales/es-es/translation.json
Hi! I'm Santos from Spain!
I would glad to contribute to this project by adding the Spanish Castilian translation, to make understandable for the people of Spain. All the string variables are translated so the user can see the translated strings of the UI in this language.
I send you cheers from Spain.
=> Spanish Castilian translation

src/plugins/image/ImageEditor.tsx
Fixes [this issue](https://github.com/mdx-editor/editor/issues/475)
Hiya! First time contributing here, do let me know if this is appropriate, it's just adding one line to address a bug I had noticed recently.
=> Added disabled property in image delete button

docs/customizing-toolbar.md, src/plugins/toolbar/index.tsx, src/plugins/toolbar/primitives/toolbar.tsx
As my second PR, I would like to introduce the possibility to customize the toolbar className. It is helpful when you would like to style the toolbar (for example dark mode).
=> feat: toolbar className customization

locales/ko-kr/translation.json
This is a Korean translation.
I did it because there are translations for each country.
You can decline if you don't want to.
=> korean lang translation

docs/getting-started.md
Correct imports added in Getting Started
=> Fix doc for Next.js (App router)

src/plugins/lists/LexicalListItemVisitor.ts
prevent insert paragraph between inline directives
=> [lexical list item visitor][fix] break line generate extra linebreak before/after text-decorator when inside list item

src/directive-editors/AdmonitionDirectiveDescriptor.tsx
=> feat: export ADMONITION_TYPES

src/index.ts
=> fix: export SandpackEditor so it can be used as a fallback

docs/search-replace.md
This serves as the start of the documentation for search and replace plugin.
Still waiting on @petyosi and thoughts on: 
https://codesandbox.io/p/github/rbbydotdev/mdx-editor-search/sandbox
For the official api and usage
=> Search replace doc

locales/de-de/translation.json
I'm a native German speaker, so I thought I should add a German translation, since I'm using this editor in one of my projects.
No AI was used for this pull request.
=> Add German translation
