- src/MDXEditor.tsx
Closes #56
Adds `focus` method to MDXEditorMethods for functionally focusing input field.
> feat: expose focus() on rootEditor

- src/MDXEditor.tsx
- src/plugins/core/index.ts
Closes #55
Lets user pass onBlur prop to listen for blur event.
> feat: add onBlur triggered by inFocus listener

- src/MDXEditor.tsx
- src/plugins/core/index.ts
Lets user pass string specifying where to set focus on `autoFocus` prop
> feat: let user choose where to autoFocus

- src/examples/images.tsx
- src/plugins/image/ImageEditor.tsx
- src/plugins/image/LexicalImageVisitor.ts
- src/plugins/image/index.ts
Here's a first draft based on what we discussed in #62 
I've added a Ladle example that updates each image to be greyscale via the picsum URL, but this handler could do anything, such as embedding base64 in the source, etc.
For simplicity, I haven't passed any of the additional props such as `title`, `width`, `height` etc to the preview handler, only the `src`, but we could do that if desired.
> feat: add a hook for updating the image source before it's rendered

- src/styles/ui.module.css
Very small UI bug I found when the editor is a little way down the page - the JSX popover can conflict with the toolbar:
To reproduce, add some padding to the JSX Example:
```jsx
<div style={{ paddingTop: 100 }}>
<MDXEditor
markdown={jsxMarkdown}
onChange={console.log}
plugins={[
jsxPlugin({ jsxComponentDescriptors }),
toolbarPlugin({
toolbarContents: () => (
<>
<InsertMyLeaf />
</>
)
})
]}
/>
</div>
```
Incrementing `z-index` seems to fix.
> fix: ensure JSX popover is displayed on top of toolbar

- src/plugins/link-dialog/LinkDialog.tsx
Hey! :wave:
Thanks for this awesome library! :smile:
Found a small bug, where the link dialog is already in a form, when clicking on the button, it submits both forms, but we only need to submit the link dialog form.
Thanks!
> fix(link-dialog): stop button submit event propagation

- src/MDXEditor.tsx
- src/plugins/core/index.ts
This migrates to an `opts` object for focus and an object for autoFocus prop. This lets users pass this option to the underlying lexical editor.
BREAKING CHANGE: use opts object instead of strings | boolean
> feat!: pass preventScroll to focus and autoFocus

- src/plugins/toolbar/components/InsertSandpack.tsx
The InsertSandpack dropdown currently uses `preset.name` as the label, we can use Sandpack `preset.label` in InsertSandpack dropdown item.
> fix: Use preset.label in InsertSandpack dropdown item

- src/plugins/sandpack/index.tsx
- src/plugins/toolbar/components/BlockTypeSelect.tsx
- src/plugins/toolbar/primitives/select.tsx
- src/plugins/toolbar/primitives/toolbar.tsx
The current dropdown items in SandpackPreset/BlockTypeSelect/toolbar only accept string as label, we can support JSX.Element to allow customized dropdown item labels, e.g. icon with label in the toolbar dropdown items.
> feat: Accept JSX.Element for various dropdown items

- docs/jsx.md
This pull request fixes some of the typos from `docs\jsx.md`. I request repository maintainers to review and merge it.
construc -> construct 
wether -> whether
> chore(docs) :fixed typos from docs\jsx.md

- src/plugins/table/index.ts
- src/plugins/toolbar/components/InsertTable.tsx
We can specify the `rows` and `columns` in `insertTable` hook to insert a initial table with the specific number of rows and columns.
https://github.com/mdx-editor/editor/assets/706422/5848ebd1-97cf-4991-946f-8d973fe9626e
> feat: Support rows and columns for insertTable

- docs/basic-formatting.md
- docs/live-demo-contents.md
- package-lock.json
- package.json
- src/examples/basics.tsx
- src/icons/format_list_checked.svg
- src/plugins/lists/LexicalListItemVisitor.ts
- src/plugins/lists/MdastListItemVisitor.ts
- src/plugins/lists/MdastListVisitor.ts
- src/plugins/lists/index.ts
- src/plugins/markdown-shortcut/index.tsx
- src/plugins/table/index.ts
- src/plugins/toolbar/components/InsertTable.tsx
- src/plugins/toolbar/components/ListsToggle.tsx
- src/styles/lexical-theme.module.css
- src/styles/lexicalTheme.ts
This is to add check list type in the current `list` plugin, the check list type is built on top of the following utilities:
1. `mdast-util-gfm-task-list-item`
2. `micromark-extension-gfm-task-list-item`
3. lexical CheckListPlugin
https://github.com/mdx-editor/editor/assets/706422/e6db49a5-f90e-4b4c-93c1-85a91409300b
> feat: Add check list type in the `list` plugin

- package.json
- scripts/generate-exports.js
- src/index.ts
This PR exports everything under `utils` for convenience when recreating components, eg for the toolbar (like `IS_APPLE` and other helpful functions / variables etc) - let me know if that's something worth doing from your pov!
> Export 'utils'

- src/plugins/toolbar/components/ChangeAdmonitionType.tsx
Update the label of ChangeAdmonitionType to capitalize the first letter of admonition name, which aligns the logic in [InsertAdmonition](https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/components/InsertAdmonition.tsx#L14)
> Capitalize admonition name for ChangeAdmonitionType

- docs/getting-started.md
This adds a brief note in the docs to more explicitly callout the css file dependency in MDXEditor - it's obviously in the code samples and the repository but I figure not everyone will jump straight into a repo and clone the code.  It can't hurt, at any rate!
> docs: update getting started, include tip on css dependency

- docs/markdown-shortcuts.md
This tripped me up so I thought I'd add a quick note in the docs.
> docs: clarify importance of order for markdown shortcuts.

- package.json
- src/plugins/codeblock/CodeBlockNode.tsx
- src/plugins/codeblock/index.ts
- src/plugins/codemirror/CodeMirrorEditor.tsx
It can be "light" | "dark" | "auto",
or the theme in "@codesandbox/sandpack-themes" package,
or you can also custom one,
just like: [sandpack docs](https://sandpack.codesandbox.io/docs/getting-started/themes#custom-theme)
> codeBlockPlugin now can set theme

- src/plugins/link-dialog/LinkDialog.tsx
- src/plugins/link-dialog/index.ts
Add  a callback for click link in **link-dialog** plugin.
So, developers can get the url that user clicked, and do some more actions.
> Add  a callback for click link in link-dialog plugin.

- src/plugins/toolbar/components/DiffSourceToggleWrapper.tsx
From https://github.com/mdx-editor/editor/discussions/338
> Possibility to select available views for diffSourcePlugin

- docs/diff-source.md
- src/examples/diff-source.tsx
- src/plugins/diff-source/DiffViewer.tsx
- src/plugins/diff-source/index.tsx
This PR will add read-only functionality to diff mode.
You can enable the read-only mode for the diff viewer in two ways:
1. Use the `readOnly` flag on the `MDXEditor` - this makes the entire editor read-only, including both the source and rich-text modes.
2. Use the `readOnlyDiff` flag on the `diffSourcePlugin` - this makes only the diff mode read-only.
For example, the code below will display the differences but prevent code editing in diff view:
```tsx
<MDXEditor
markdown={'hello world'}
plugins={[
diffSourcePlugin({
diffMarkdown: 'An older version',
viewMode: 'diff',
readOnlyDiff: true
})
]}
/>
```
And this code will prevent any code changes in any mode:
```tsx
<MDXEditor
markdown={'hello world'}
readOnly={true}
plugins={[
diffSourcePlugin({
diffMarkdown: 'An older version',
viewMode: …
```
> Add readOnlyDiff parameter to diffSourcePlugin

- docs/jsx.md
- src/examples/basics.tsx
- src/examples/jsx.tsx
- src/jsx-editors/GenericJsxEditor.tsx
- src/plugins/core/index.ts
- src/plugins/jsx/index.ts
This pull-request will introduce support for expression properties in JSX components. It will add support for handling fragments (`<></>`) as well.
**Description:**
There are two types of properties - "textual" and "expressions" in JSX. You can define type in `JsxComponentDescriptor`. `jsxPlugin` will treat the value based on this setting. For example, this code:
```tsx
const jsxComponentDescriptors: JsxComponentDescriptor[] = [
{
name: 'MyLeaf',
kind: 'text',
props: [
{ name: 'foo', type: 'string' } // Textual property type
],
hasChildren: true,
Editor: GenericJsxEditor
}
]
```
will produce component like the following:
```tsx
<MyLeaf foo="bar">Some text...</MyLeaf>
```
While this descriptor:
```tsx
const jsxComponentDescriptors: JsxComponentDescriptor[] = [
{
name: 'MyLeaf',
kind: …
```
> Add support for expression properties into JSX plugin

- docs/links.md
Fix tiny typo in Links documentation where the semicolon was misplaced.
> fix(docs): fix typo in links docs

- src/plugins/table/TableEditor.tsx
- src/styles/ui.module.css
This is a PR to fix issue https://github.com/mdx-editor/editor/issues/411
Replacing `td` with `th` element in the table editor to provide some visual difference.
1. Pull down the branch
2. Run `npm run dev`
3. Navigate to http://localhost:61000/?story=basics--table
4. Confirm that the header looks as per screenshot
5. Confirm you can add rows after and before the header
> fix(table-editor): first row should be a header row using th instead of td element

- src/styles/ui.module.css
Using iOS safari, if I open an mdx-editor page and do the following:
1. select the bold option
2. deselect the bold option
The result will be the bold option appears to be selected because its "hover" styling has been triggered. This is a common issue with touch devices that do not support hover. This change gates :hover behind media queries that filter only for devices that support it.
> fix: ignore :hover css style on touch devices.

- src/plugins/table/TableEditor.tsx
This is a fix for issue #451 
If the table propagates the `NESTED_EDITOR_UPDATED_COMMAND` in the same way as the `NestedLexicalEditor`, it can update correctly when inside one. This also requires the table's `parentEditor.update` to be discrete like the update in `NestedLexicalEditor` so any parent editors get the newly updated table when they update.
> Fix updating of table inside nested editor

- src/MDXEditor.tsx
- src/plugins/toolbar/primitives/toolbar.tsx
The code changes add `aria-label` attributes to the `MDXEditor` and `SingleChoiceToggleGroup` components to improve accessibility.
closes #459
> feat: Add aria-label to MDXEditor and SingleChoiceToggleGroup

- .eslintrc.cjs
- package-lock.json
- package.json
This should fix https://github.com/mdx-editor/editor/issues/481
When running the build, you can see this import in the compiled file. This is wrong.
- also add eslint rules to prevent this from happening again
- With the eslint rule on, you can see before screenshot. After making imports explicit in package json
> fix(deps): fix micromark-extension-gfm-strikethrough not being externalised

- src/plugins/toolbar/components/CreateLink.tsx
Added aria-label to improve accessibility
closes #493
> feat: Add aria-label to CreateLink button

- locales/pt-br/translation.json
The following translations were added to the pt-br.json locale file:
- toolbar.superscript: "Sobrescrito"
- toolbar.subscript: "Subescrito"
- toolbar.strikethrough: "Riscado"
> additional translations in pt-br

- src/examples/images.tsx
- src/plugins/image/ImageDialog.tsx
- src/plugins/image/ImageNode.tsx
- src/plugins/image/index.ts
1. `ImageDialog` now properly accepts links using a hidden input.
2. Fixed drag-and-drop plus copy-and-paste by taking advantage of differences in `DataTransferItemList` type (see attached PDF)
3. Removed imageUploadHandler on `ImageWithNoBackend` example
[MDXEditor_data_types_and_call_sequence.pdf](https://github.com/user-attachments/files/16354250/MDXEditor.pdf)
> Fix: prevent file system D&D, C&P, upload if no uploadImageHandler

- src/index.ts
Provide a fix for the #545
Export both `IconKey` type (to use in the `iconComponentFor` prop) and the `defaultSvgIcons` constant to override icons properly
> Export default icons for toolbar customization

- src/plugins/core/NestedLexicalEditor.tsx
- src/plugins/table/TableEditor.tsx
Provides a suggested fix for #528 
Adds a focus command listener to NestedLexicalEditor to prevent this event being captured by TableCell instead.
Lowers the priority of the blur command on TableCell to match NestedLexicalEditor.
> Fix NestedLexicalEditor focus and update from within TableCell

- src/plugins/image/ImageEditor.tsx
- src/plugins/image/index.ts
Make it possible to hide the image toolbar, e.g. when editor is in readOnly mode.
When using the editor to just render documents (e.g. in an application where some users only have viewing capabilities), even with hidden toolbar and read only mode, each image will still show the toolbar (settings + delete icon). Other plugins, like the table, hide their toolbar already when in read only mode. This makes it possible to get to the same state with the image plugin, alternatively, it could also make sense to always hide the toolbar when in read only mode.
> feat: add `hideImageToolbar` option to imagePlugin

- src/plugins/table/TableEditor.tsx
This is to address #570
Currently no other plugins have a priority higher than EDITOR for this action, so this allows the command to bubble up the hierarchy in order
> Reduce update command priority on Table Cell

- src/MDXEditor.tsx
- src/plugins/core/index.ts
When using diffSourcePlugin with viewmode=source, this trim() would cause MDXEditor's onChange to fire immediately. This in turn would dirty the field when used in combination with a form wrapper like
react-hook-form.
I think the initial markdown does not need to be trimmed; the user should be free to initialize the editor with trailing or leading newlines as they see fit, the editor should not care.
> Don't trim initial markdown

- locales/en/translation.json
- locales/es-es/translation.json
- locales/pt-br/translation.json
- locales/uk-ua/translation.json
- locales/zh-cn/translation.json
- locales/zh-tw/translation.json
- src/plugins/image/ImageDialog.tsx
Due to the changes made by the radix (and screen readers API). Using `ImageDialog` without `Dialog.Title` component will result in errors in the console. 
I have also added the translations to keep everything up-to-date.
> fix: image dialog missing title

- src/MDXEditor.tsx
- src/plugins/core/index.ts
* adds spellCheck as discussed here: https://github.com/mdx-editor/editor/discussions/351
> feat: add spellCheck prop for content editable element

- docs/getting-started.md
Was going through the nextjs installation and noticed that two imports were missing in the code snippet given. It's not a huge issue, but figured it's easier to have it on there and ready for copy-pasta.
> Docs - Getting Started - Next.js (App) - missing imports

- locales/en/translation.json
- locales/es-es/translation.json
- locales/ko-kr/translation.json
- locales/pt-br/translation.json
- locales/uk-ua/translation.json
- locales/zh-cn/translation.json
- locales/zh-tw/translation.json
- src/plugins/image/ImageEditor.tsx
While adding support for multiple languages, I noticed that the translation for "Delete image" was not working. Upon investigation, I found that the key for "Delete image" was missing under imageEditor.
Currently, to apply the correct translation, we need to use image.delete:
```json
{
"image": {
"delete": "Delete image"
},
"imageEditor": {
"editImage": "Edit image"
}
}
```
Expected Update
Move the "Delete image" key under imageEditor for consistency:
```json
{
"imageEditor": {
"deleteImage": "Delete image",
"editImage": "Edit image"
}
}
```
As a non-native English speaker, I welcome any suggestions for improvement.
> fix: i18n key for delete image functionality

- src/plugins/table/index.ts
`Table` `Plugin` now takes in the same `Options` as `gfmTable` and passes them on
> [Feat] Table params

- src/plugins/image/index.ts
Currently, if you copy text from MS Word into the mdx-editor with the image plugin enabled, the content will be pasted as image. This is because MS Word (at least on a mac) adds the copied selection as plaintext, html, rtf and as *image* to the systems paste buffer. The Paste Command in the image plugin, intercepted the paste since an image was in the buffer.
This fix only allows the paste command in the image plugin to intercept the pasting if the paste buffer exclusively contains images.
Here is a video comparing the previous and the new behavior:
https://github.com/user-attachments/assets/ccc87ca7-a47d-4c79-9e78-d7d51d37f9de
> Only paste as image if payload does not contain text content

- src/plugins/table/index.ts
Fixed a Prettier formatting issue in src/plugins/table/index.ts on line 92 that caused the release pipeline to fail.
> fix: linter error in src/plugins/table/index.ts 92l

- src/jsx-editors/GenericJsxEditor.tsx
This PR just adds a hook to override the property editor of the GenericJsxEditor.  
The GenericEditor has a nice layout for the NestedLexicalEditor, and access to all of the built in styles.  So this just allows passing a custom property editor and having the generic editor use it instead of the PropertyPopover, for times when you want a more customized editing experience.
> feat(GenericJsxEditor): customizable property editor

- src/plugins/lists/LexicalListItemVisitor.ts
Fixes #706 
Other cases seem to be working fine:
> fix: preserve line breaks in list items

- src/plugins/link-dialog/index.ts
Fixes #619 and #695.
The code was mostly taken from `src/plugins/core/index.ts`
> fix: hide link dialog when switching view modes

- src/plugins/markdown-shortcut/index.tsx
- src/plugins/thematic-break/index.ts
This PR adds support for typing `---` or `***` or `___` to insert a thematic break node (Horizontal rule).
Sadly, as in of Lexical basic MarkdownShortcuts plugin, one needs to press space immediately after the trigger characters, and it does not work if one presses enter immediately. 
It would be nice to address the issue in a separate MR
> Add Markdown Shortcut for thematic break (HR)

- src/examples/directives.tsx
- src/plugins/directives/MdastDirectiveVisitor.ts
- src/plugins/directives/index.ts
When editing german text, a colon is often used to separate words. Since the separated word is treated as a directive, the mdx editor will either show an error message or the `GenericDirectiveDescriptor` is used to catch all unknown occurences, what leads to an unwanted behavior.
This PR allows to configure the MdastDirectiveVisitor to accept the option `escapeUnknownTextDirectives`. In this case unknwon `textDirectives` are rendered as text instead of mdastDirectives.
```md
Alle Schüler:innen der Schule.
```
would be rendered as
```
Alle Schüler\:innen der Schule.
```
> feat: add option to escape unknown text directives

- src/plugins/image/ImageDialog.tsx
- src/plugins/link-dialog/LinkDialog.tsx
After emitting a lot of keystrokes the editor (that uses link & image dialog) become so laggy because both dialogs re-rendered in every keystores.
this issue can easily reproduced on the live demo
https://github.com/user-attachments/assets/109429fe-aba4-436f-a10f-8442e7c7f002
return null instead of component if the current state not relevant to each dialogs
> fix: link & image dialog re-renders issue that causes editor laggy

- src/plugins/image/EditImageToolbar.tsx
- src/plugins/image/ImageEditor.tsx
- src/plugins/image/index.ts
While trying to integrate MDXEditor into my project i ran across an issue where all images had the edit image toolbar which was not astetically alligned with the styling of my website.
The goal of this pr is to allow to customize the toolbar with my own component so i can have a more coherent look to my website.
Thanks!
> Add ability to modify the image editor toolbar

- src/MDXEditor.tsx
- src/examples/within-dialog.tsx
fix: Enables setting the overlayContainer on MDXEditor so the implementer can control in which HTML element the popup containers are shown. This enables the usage of MDXEditor within <dialog> HTML elements.
See #752
> Add overlayContainer prop so overlay location can be controlled.

- src/plugins/image/index.ts
When changing the source of a current image in the image dialog plugin you get the following error
```
values.file is undefined
TypeError
TypeError: values.file is undefined
```
This is due to the file form field not having a value when editing an existing image node. (_This behavior is likely expected_ ?) 
Therefore checking first if the field is not undefined before checking its length mitigates the error.
The changes in this PR reflect this.
> Fix error in image dialog plugin when changing src of image

- src/plugins/image/ImageEditor.tsx
- src/plugins/image/index.ts
- src/styles/ui.module.css
This PR does two things
- Uses a cache mechanism for the suspended promise for lazy image, this prevents multiple promises for the same image when the component re-renders
- Adds a default image placeholder while image is loading (see attached image),`imagePlaceholder` is also made as an option for the image plugin
> image placeholder and image suspense cache

- src/plugins/image/index.ts
This update allows drag and drop image plugin to use type string in dataTransfer item. Currently just File instance types are supported. This enhancement is specifically for internal (in-browser) image drag-and-drop functionality. By using the `getAsString` method, the URL of the image is directly retrieved, bypassing the imageUploadHandler function by using the url contained in the string dataTransfer item value.
When using a file explorer within the browser, dragging an image from the explorer to the editor does not work in Chrome or Safari. This limitation arises because these browsers do not allow `File` objects to be added to the `dataTransfer` items, preventing access to them in the drop handler.
Current support allows the use case of dragging from external explorers into the …
> Allow drag and drop image plugin to use type string in dataTransfer item

- src/plugins/image/ImageEditor.tsx
- src/plugins/image/index.ts
when an image does not load, the following placeholder will show indicating an issue loading.
This also remedies (#770 ) the lack of img.onerror in the lazy error image handler. the problem was just the placeholder showing upon error, making it difficult to delete or edit the image
> Img error placeholder shows error

- locales/fr/translation.json
This PR adds full support for the French locale (`fr`) in the MDX Editor interface.  
It includes translations for all keys currently available in the default English locale:
- Frontmatter editor
- Toolbar actions
- Image & link dialogs
- Table controls
- Admonitions
- Code block options
- Global UI strings
All strings were carefully reviewed for clarity and consistency with professional French terminology.
> Create French translation ! 🇫🇷🥖

- src/exportMarkdownFromLexical.ts
- src/importMarkdownToLexical.ts
A new skip function added to actions of the visitors for both markdown import and export visits
This is helpful when extending via `addImportVisitor` or `addExportVistor`, you may want to inspect(/and modify) the tree but allow further processing from the visitors already in place 
```typescript
const LogMdastTextVisitor: MdastImportVisitor<Mdast.Text> = {
testNode: "text",
visitNode({ mdastNode, actions }) {
console.log(`TEXT NODE: ${mdastNode.value} at ${mdastNode.position?.start.line}:${mdastNode.position?.start.column}`);
actions.skip();
},
priority: 1000,
};
```
Also `actions.next` may be more appropriate
> skip fn in visitor actions in import and export markdown visit functions

- src/index.ts
It would be nice to share the lexical module used internally, this is especially handy during some extensions. Maintaining another lexical dep in my project is a bit hairy. _I think i'm doing this right?_
I feel like this should be fine as long as the lexical export is properly tree shaken
> export lexical so it can be used during extension
